trigger:
    branches:
      include:
      - master
      - preview
      - release-*
    paths:
      exclude:
      - CHANGELOG.md
pr: none
stages:
 - stage: Build
   displayName: Build
   jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'

      variables:
        buildConfiguration: 'Release'

      steps:
        - checkout: self
          clean: true
          persistCredentials: true

        - task: UseDotNet@2
          displayName: 'Use .NET 8 Core sdk'
          enabled: false
          inputs:
            packageType: sdk
            version: 8.0.x
            installationPath: $(Agent.ToolsDirectory)/dotnet

        - task: DotNetCoreCLI@2
          name: Publish_Api
          enabled: true
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: 'Cronus.Monitor/Cronus.Monitor/Cronus.Monitor.Api.csproj'
            arguments: '/p:Configuration=Release --output $(Build.ArtifactStagingDirectory)/api'
            zipAfterPublish: false
            modifyOutputPath: false

        - task: Bash@3
          name: Release
          env:
            STAGING_PATH: $(Build.ArtifactStagingDirectory)
            LOCAL_PATH: $(Build.Repository.LocalPath)
            DOCKER_HUB_PASSWORD: $(DOCKER_HUB_PASSWORD)
          inputs:
            targetType: 'inline'
            script: |
              time curl -L https://github.com/Elders/blob/releases/download/SemRel-01/node_modules.tar.gz | tar -xzv
              RELEASE_OUTPUT=$(npx semantic-release --no-ci)
              echo "$RELEASE_OUTPUT"
             # if [[ "$RELEASE_OUTPUT" == *"Published"* ]]; then
              #  echo "##vso[task.setvariable variable=Released;isOutput=true]true"
            #  else
            #    echo  "##vso[task.setvariable variable=Released;isOutput=true]false"
            #  fi
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: 'ci'
            artifact: 'manifest'
            publishLocation: 'pipeline'
