FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine

COPY service /service

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT false
RUN apk add --no-cache icu-libs tzdata

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

STOPSIGNAL SIGINT

WORKDIR /service
CMD ["dotnet", "UniCom.Monitor.Service.dll"]